spring.application.name=cqrsquery
server.port=8081
spring.main.allow-bean-definition-overriding=true

# Mongo DB
spring.mongodb.uri=mongodb://admin:uptc2026@localhost:27017/orders?authSource=admin
spring.mongodb.database=orders
logging.level.org.springframework.data.mongodb.core=DEBUG

# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=customer-query-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer